# Generated by Django 5.0.4 on 2024-10-31 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecomercio', models.CharField(db_column='nombreComercio', max_length=30)),
                ('cuit', models.BigIntegerField(max_length=11, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.PositiveIntegerField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comercios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oferente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ubicacionesComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=100)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.CharField(blank=True, max_length=20, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('comercio_id', models.OneToOneField(blank=True, db_column='oferente_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='oferente.oferente')),
                ('departamento', models.ForeignKey(db_column='cod_depto', null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.tabladepartamento')),
                ('localidad', models.ForeignKey(db_column='cod_ase', null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.tablalocalidad')),
                ('municipio', models.ForeignKey(db_column='cod_agl', null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.tablamunicipio')),
                ('pais', models.ForeignKey(db_column='cod_pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.tablapais')),
                ('provincia', models.ForeignKey(db_column='cod_pcia', null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.tablaprovincia')),
            ],
            options={
                'verbose_name': 'ubicacion_comercio',
                'db_table': 'ubicacion_comercio',
                'managed': True,
            },
        ),
    ]
