# Generated by Django 5.0.4 on 2024-12-11 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oferente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='oferente',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferentes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oferente',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferentes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oferente',
            name='usuario_eliminacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oferentes_eliminados', to=settings.AUTH_USER_MODEL),
        ),
    ]
