# Generated by Django 5.0.6 on 2024-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='cuit',
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
