# Generated by Django 5.0.6 on 2024-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0002_alter_oferente_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='cuit',
            field=models.BigIntegerField(max_length=11, unique=True),
        ),
    ]
