# Generated by Django 5.0.4 on 2024-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0008_alter_oferente_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='nombrecomercio',
            field=models.CharField(db_column='nombreComercio'),
        ),
    ]
