# Generated by Django 5.0.4 on 2024-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0010_alter_oferente_cuit_alter_oferente_nombrecomercio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='cuit',
            field=models.BigIntegerField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
