# Generated by Django 5.0.4 on 2024-10-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0011_alter_oferente_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='cuit',
            field=models.BigIntegerField(max_length=11, unique=True),
        ),
    ]
