# Generated by Django 5.0.4 on 2024-10-31 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0012_alter_oferente_cuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacionescomercio',
            options={'managed': True, 'verbose_name': 'ubicacion_comercio'},
        ),
        migrations.AlterField(
            model_name='ubicacionescomercio',
            name='comercio_id',
            field=models.OneToOneField(blank=True, db_column='oferente_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='oferente.oferente'),
        ),
        migrations.AlterModelTable(
            name='ubicacionescomercio',
            table='ubicacion_comercio',
        ),
    ]
