# Generated by Django 5.0.4 on 2024-10-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferente', '0012_alter_oferente_cuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacionescomercio',
            options={'managed': True, 'verbose_name': 'Ubicacion comercio', 'verbose_name_plural': 'Ubicaciones comercio'},
        ),
    ]
