# Generated by Django 5.0.4 on 2024-12-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_maxima_ofertas', models.PositiveIntegerField(default=5, verbose_name='Cantidad máxima de ofertas')),
                ('formatos_imagen_permitidos', models.CharField(default='jpg,png', help_text='Introduce los formatos separados por comas, por ejemplo: jpg,png', max_length=5, verbose_name='Formatos de imagen permitidos')),
            ],
        ),
    ]
