# Generated by Django 5.0.4 on 2024-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='formatos_imagen_permitidos',
            field=models.CharField(default='jpg,png', help_text='Introduce los formatos separados por comas, por ejemplo: jpg,png', max_length=200, verbose_name='Formatos de imagen permitidos'),
        ),
    ]
