# Generated by Django 5.0.4 on 2024-10-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSupabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'productos_supabase',
                'managed': False,
            },
        ),
    ]
