# Generated by Django 5.0.4 on 2024-10-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_productosupabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoSupabase',
        ),
    ]
