# Generated by Django 5.0.4 on 2024-12-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_subcategoria_eliminado_subcategoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
