# Generated by Django 5.0.4 on 2024-10-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
