# Generated by Django 5.0.4 on 2024-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0002_oferta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='eliminado',
            field=models.BooleanField(default=True),
        ),
    ]
