# Generated by Django 5.0.4 on 2024-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0003_oferta_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
