# Generated by Django 5.0.4 on 2024-12-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta', '0006_oferta_fecha_creacion_oferta_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='titulo',
            field=models.TextField(max_length=50),
        ),
    ]
