# Generated by Django 5.0.4 on 2024-05-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50, unique=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('clave', models.CharField(max_length=10, verbose_name='Clave')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion_token', models.DateTimeField(blank=True, null=True)),
                ('actividad_inicio', models.DateTimeField(blank=True, null=True)),
                ('actividad_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario_creacion', models.PositiveIntegerField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.PositiveIntegerField(blank=True, null=True)),
                ('persona_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('rol_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
