# Generated by Django 5.0.4 on 2024-05-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_groups_usuario_is_staff_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_administrador',
        ),
    ]
