# Generated by Django 5.0.4 on 2024-05-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='persona_id',
        ),
    ]
