# Generated by Django 5.0.6 on 2024-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_usuario_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion_token',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
