# Generated by Django 5.0.6 on 2024-06-03 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_fecha_creacion_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Introduzca un nombre de usuario valido. Este solo puede incluir letras y numeros', regex='^[a-zA-Z0-9]{4,15}*$')], verbose_name='Nombre de usuario'),
        ),
    ]
