# Generated by Django 5.0.4 on 2024-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_fecha_creacion_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='metodo_verificacion',
            field=models.CharField(default='email', max_length=80),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=40, null=True, verbose_name='SU TELEFONO: '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
