# Generated by Django 5.0.4 on 2024-09-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0013_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
