# Generated by Django 5.0.4 on 2024-09-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_remove_usuario_actividad_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
