# Generated by Django 5.0.4 on 2024-09-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_registroactividad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroActividad',
        ),
    ]
