# Generated by Django 5.0.4 on 2024-09-17 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0018_delete_registroactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
