# Generated by Django 5.0.4 on 2024-09-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_alter_actividadusuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='permisos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='actividad_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='actividad_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='metodo_verificacion',
            field=models.CharField(default='email', max_length=80),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=40, null=True, verbose_name='SU TELEFONO: '),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
