# Generated by Django 5.0.4 on 2024-10-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TablaDepartamento',
            fields=[
                ('cod_depto', models.CharField(primary_key=True, serialize=False)),
                ('nom_depto', models.CharField(blank=True, null=True)),
                ('provincia_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaLocalidad',
            fields=[
                ('cod_ase', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, null=True)),
                ('lat_gd', models.CharField(blank=True, null=True)),
                ('long_gd', models.CharField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, null=True)),
                ('municipio_id_id', models.CharField(blank=True, null=True)),
                ('lat_gs', models.CharField(blank=True, null=True)),
                ('long_gs', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_localidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaMunicipio',
            fields=[
                ('cod_agl', models.CharField(primary_key=True, serialize=False)),
                ('nom_agl', models.CharField(blank=True, null=True)),
                ('departamento_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPais',
            fields=[
                ('cod_pais', models.CharField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaProvincia',
            fields=[
                ('cod_pcia', models.CharField(primary_key=True, serialize=False)),
                ('nom_pcia', models.CharField(blank=True, null=True)),
                ('pais_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('identificacion', models.IntegerField(help_text='Ingrese el nro de dni sin puntos', primary_key=True, serialize=False, verbose_name='D.N.I.')),
                ('nombres', models.CharField(help_text='Si posee mas de un nombre ingrese los mismos con un espacio entre cada nombre. Ej: Juan Carlos', max_length=50)),
                ('apellidos', models.CharField(blank=True, help_text='Si posee mas de un apellido ingrese los mismos con un espacio entre cada apellido. Ej: Rodriguez Perez', max_length=25, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No Binario')], max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('foto', models.ImageField(blank=True, default='avatar_default.png', null=True, upload_to='personas/')),
                ('usuario_creacion', models.PositiveIntegerField(blank=True, null=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=100)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.CharField(blank=True, max_length=20, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('departamento', models.ForeignKey(db_column='cod_depto', on_delete=django.db.models.deletion.CASCADE, to='persona.tabladepartamento')),
                ('localidad', models.ForeignKey(db_column='cod_ase', on_delete=django.db.models.deletion.CASCADE, to='persona.tablalocalidad')),
                ('municipio', models.ForeignKey(db_column='cod_agl', on_delete=django.db.models.deletion.CASCADE, to='persona.tablamunicipio')),
                ('pais', models.ForeignKey(db_column='cod_pais', on_delete=django.db.models.deletion.CASCADE, to='persona.tablapais')),
                ('persona_id', models.OneToOneField(blank=True, db_column='identificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='persona.persona')),
                ('provincia', models.ForeignKey(db_column='cod_pcia', on_delete=django.db.models.deletion.CASCADE, to='persona.tablaprovincia')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
            },
        ),
    ]
