# Generated by Django 5.0.4 on 2024-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='genero',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='identificacion',
            field=models.CharField(help_text='Ingrese el nro de dni sin puntos', max_length=10, primary_key=True, serialize=False),
        ),
    ]
