# Generated by Django 5.0.4 on 2024-05-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_persona_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.IntegerField(help_text='Ingrese el nro de dni sin puntos', max_length=10, primary_key=True, serialize=False, verbose_name='D.N.I.'),
        ),
    ]
