# Generated by Django 5.0.4 on 2024-05-27 16:03

import persona.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_persona_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, default='avatar_default.png', null=True, upload_to=persona.models.get_file_path),
        ),
    ]
