# Generated by Django 5.0.6 on 2024-06-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_tabladepartamento_tablalocalidad_tablamunicipio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='persona',
            new_name='persona_id',
        ),
    ]
