# Generated by Django 5.0.6 on 2024-06-12 00:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_rename_persona_ubicaciones_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(blank=True, help_text='Si posee mas de un apellido ingrese los mismos con un espacio entre cada apellido. Ej: Rodriguez Perez', max_length=25, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un dato válido. Sólo se permiten letras, espacios, guiones y apóstrofes', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]{2,25}( [a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]{2,25})*$')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.IntegerField(help_text='Ingrese el nro de dni sin puntos', primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Ingrese un numero de DNI válido. Solo se permiten 8 digitos númericos.', regex='^[0-9]{8}$')], verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(blank=True, help_text='Si posee mas de un nombre ingrese los mismos con un espacio entre cada nombre. Ej: Juan Carlos', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un dato válido. Sólo se permiten letras, espacios, guiones y apóstrofes', regex='^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]{2,25}( [a-zA-ZáéíóúÁÉÍÓÚüÜñÑ]{2,25})*$')]),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='departamento',
            field=models.ForeignKey(db_column='cod_depto', on_delete=django.db.models.deletion.CASCADE, to='persona.tabladepartamento'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='localidad',
            field=models.ForeignKey(db_column='cod_ase', on_delete=django.db.models.deletion.CASCADE, to='persona.tablalocalidad'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='municipio',
            field=models.ForeignKey(db_column='cod_agl', on_delete=django.db.models.deletion.CASCADE, to='persona.tablamunicipio'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='pais',
            field=models.ForeignKey(db_column='cod_pais', on_delete=django.db.models.deletion.CASCADE, to='persona.tablapais'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='persona_id',
            field=models.OneToOneField(blank=True, db_column='identificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaion', to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='provincia',
            field=models.ForeignKey(db_column='cod_pcia', on_delete=django.db.models.deletion.CASCADE, to='persona.tablaprovincia'),
        ),
    ]
