# Generated by Django 5.0.4 on 2024-09-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_alter_persona_apellidos_alter_persona_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(blank=True, help_text='Si posee mas de un apellido ingrese los mismos con un espacio entre cada apellido. Ej: Rodriguez Perez', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.IntegerField(help_text='Ingrese el nro de dni sin puntos', primary_key=True, serialize=False, verbose_name='D.N.I.'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(help_text='Si posee mas de un nombre ingrese los mismos con un espacio entre cada nombre. Ej: Juan Carlos', max_length=50),
        ),
    ]
