# Generated by Django 5.0.4 on 2024-09-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_alter_persona_apellidos_alter_persona_identificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_departamento',
            fields=[
                ('cod_depto', models.CharField(primary_key=True, serialize=False)),
                ('nom_depto', models.CharField(blank=True, null=True)),
                ('provincia_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabla_localidad',
            fields=[
                ('cod_ase', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, null=True)),
                ('lat_gd', models.CharField(blank=True, null=True)),
                ('long_gd', models.CharField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, null=True)),
                ('municipio_id_id', models.CharField(blank=True, null=True)),
                ('lat_gs', models.CharField(blank=True, null=True)),
                ('long_gs', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_localidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabla_municipio',
            fields=[
                ('cod_agl', models.CharField(primary_key=True, serialize=False)),
                ('nom_agl', models.CharField(blank=True, null=True)),
                ('departamento_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabla_pais',
            fields=[
                ('cod_pais', models.CharField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabla_provincia',
            fields=[
                ('cod_pcia', models.CharField(primary_key=True, serialize=False)),
                ('nom_pcia', models.CharField(blank=True, null=True)),
                ('pais_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_provincia',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='departamento',
            field=models.ForeignKey(db_column='cod_depto', on_delete=django.db.models.deletion.CASCADE, to='persona.tabla_departamento'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='localidad',
            field=models.ForeignKey(db_column='cod_ase', on_delete=django.db.models.deletion.CASCADE, to='persona.tabla_localidad'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='municipio',
            field=models.ForeignKey(db_column='cod_agl', on_delete=django.db.models.deletion.CASCADE, to='persona.tabla_municipio'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='pais',
            field=models.ForeignKey(db_column='cod_pais', on_delete=django.db.models.deletion.CASCADE, to='persona.tabla_pais'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='provincia',
            field=models.ForeignKey(db_column='cod_pcia', on_delete=django.db.models.deletion.CASCADE, to='persona.tabla_provincia'),
        ),
        migrations.DeleteModel(
            name='TablaDepartamento',
        ),
        migrations.DeleteModel(
            name='TablaLocalidad',
        ),
        migrations.DeleteModel(
            name='TablaMunicipio',
        ),
        migrations.DeleteModel(
            name='TablaPais',
        ),
        migrations.DeleteModel(
            name='TablaProvincia',
        ),
    ]
