# Generated by Django 5.0.6 on 2024-09-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_tabla_departamento_tabla_localidad_tabla_municipio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaDepartamento',
            fields=[
                ('cod_depto', models.CharField(primary_key=True, serialize=False)),
                ('nom_depto', models.CharField(blank=True, null=True)),
                ('provincia_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaLocalidad',
            fields=[
                ('cod_ase', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, null=True)),
                ('lat_gd', models.CharField(blank=True, null=True)),
                ('long_gd', models.CharField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, null=True)),
                ('municipio_id_id', models.CharField(blank=True, null=True)),
                ('lat_gs', models.CharField(blank=True, null=True)),
                ('long_gs', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_localidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaMunicipio',
            fields=[
                ('cod_agl', models.CharField(primary_key=True, serialize=False)),
                ('nom_agl', models.CharField(blank=True, null=True)),
                ('departamento_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaPais',
            fields=[
                ('cod_pais', models.CharField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TablaProvincia',
            fields=[
                ('cod_pcia', models.CharField(primary_key=True, serialize=False)),
                ('nom_pcia', models.CharField(blank=True, null=True)),
                ('pais_id_id', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tabla_provincia',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='persona_id',
            field=models.OneToOneField(blank=True, db_column='identificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='persona.persona'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='departamento',
            field=models.ForeignKey(db_column='cod_depto', on_delete=django.db.models.deletion.CASCADE, to='persona.tabladepartamento'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='localidad',
            field=models.ForeignKey(db_column='cod_ase', on_delete=django.db.models.deletion.CASCADE, to='persona.tablalocalidad'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='municipio',
            field=models.ForeignKey(db_column='cod_agl', on_delete=django.db.models.deletion.CASCADE, to='persona.tablamunicipio'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='pais',
            field=models.ForeignKey(db_column='cod_pais', on_delete=django.db.models.deletion.CASCADE, to='persona.tablapais'),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='provincia',
            field=models.ForeignKey(db_column='cod_pcia', on_delete=django.db.models.deletion.CASCADE, to='persona.tablaprovincia'),
        ),
        migrations.DeleteModel(
            name='tabla_departamento',
        ),
        migrations.DeleteModel(
            name='tabla_localidad',
        ),
        migrations.DeleteModel(
            name='tabla_municipio',
        ),
        migrations.DeleteModel(
            name='tabla_pais',
        ),
        migrations.DeleteModel(
            name='tabla_provincia',
        ),
    ]
