# Generated by Django 5.0.4 on 2024-09-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_tabladepartamento_tablalocalidad_tablamunicipio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='persona_id',
            field=models.OneToOneField(blank=True, db_column='identificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='persona.persona'),
        ),
    ]
