# Generated by Django 5.0.4 on 2024-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_alter_ubicaciones_persona_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
